[package]
name = "ft_ls"
version = "0.1.0"
authors = ["jkuusist <jkuusist@student.hive.fi>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
users = "0.11"
term_size = "0.3.2"
